### ISSUE TITLE
Cannot evaluate DependentCoordinates

### ISSUE THREAD

**Issue by jmilloy** [creare-com/podpac#280]
**Steps to Reproduce**

```
import podpac
node = podpac.algorithm.Arange()
c = podpac.Coordinates([[[1, 2, 3], [10, 20, 30]]], dims=['lat,lon'])
node.eval(c)
```

**Expected Behavior**

The node should evaluate to `[0, 1, 2]`.

**Observed Behavior**

```
Traceback (most recent call last):
  File "/home/jmilloy/Creare/Pipeline/_podpac_/lib/python3.6/site-packages/xarray/core/variable.py", line 84, in as_variable
    obj = Variable(*obj)
  File "/home/jmilloy/Creare/Pipeline/_podpac_/lib/python3.6/site-packages/xarray/core/variable.py", line 265, in __init__
    self._dims = self._parse_dimensions(dims)
  File "/home/jmilloy/Creare/Pipeline/_podpac_/lib/python3.6/site-packages/xarray/core/variable.py", line 443, in _parse_dimensions
    % (dims, self.ndim))
ValueError: dimensions ('i', 'j') must have the same length as the number of data dimensions, ndim=1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jmilloy/Creare/Pipeline/podpac/podpac/core/node.py", line 538, in wrapper
    data = fn(self, coordinates, output=output)
  File "/home/jmilloy/Creare/Pipeline/podpac/podpac/core/algorithm/algorithm.py", line 81, in eval
    result = self.algorithm(inputs)
  File "/home/jmilloy/Creare/Pipeline/podpac/podpac/core/algorithm/algorithm.py", line 161, in algorithm
    return self.create_output_array(self._requested_coordinates, data=data)
  File "/home/jmilloy/Creare/Pipeline/podpac/podpac/core/node.py", line 237, in create_output_array
    return create_data_array(coords, data=data, dtype=self.dtype, attrs=attrs, **kwargs)
  File "/home/jmilloy/Creare/Pipeline/podpac/podpac/core/units.py", line 292, in create_data_array
    return UnitsDataArray(data, coords=coords.coords, dims=coords.idims, **kwargs)
  File "/home/jmilloy/Creare/Pipeline/podpac/podpac/core/coordinates/coordinates.py", line 705, in coords
    x = xr.DataArray(np.empty(self.shape), dims=self.idims, coords=coords)
  File "/home/jmilloy/Creare/Pipeline/_podpac_/lib/python3.6/site-packages/xarray/core/dataarray.py", line 231, in __init__
    coords, dims = _infer_coords_and_dims(data.shape, coords, dims)
  File "/home/jmilloy/Creare/Pipeline/_podpac_/lib/python3.6/site-packages/xarray/core/dataarray.py", line 64, in _infer_coords_and_dims
    new_coords[k] = as_variable(v, name=k)
  File "/home/jmilloy/Creare/Pipeline/_podpac_/lib/python3.6/site-packages/xarray/core/variable.py", line 89, in as_variable
    '{} to Variable.'.format(obj))
ValueError: Could not convert tuple of form (dims, data[, attrs, encoding]): (('i', 'j'), array([0., 1., 2.])) to Variable.
```

**Additional Notes**

There may be additional issues, especially if an `output` is provided to `node.eval`, due to the fact that the coordinates dims and the output dims don't match. I was initially testing to see if the `node_eval` wrapper needed to be updated to use `idims` when transposing, and the above error prevents checking that.

```
        # transpose data to match the dims order of the requested coordinates
        order = [dim for dim in coordinates.idims if dim in data.dims]
        data = data.transpose(*order)

```

**Comment by jmilloy** [comment]
It looks like there are also (different) issues with native_coordinates with DependentCoordinates:

```
node = podpac.data.Array(source=np.random.random((3, 3)), native_coordinates=c)
node.eval(c)
```

**Comment by jmilloy** [comment]
This is also working in v3.0. I think merging dependent coordinates into stacked coordinates fixed this issue as well.

```
In [11]: import podpac
    ...: node = podpac.algorithm.Arange()
    ...: c = podpac.Coordinates([[[1, 2, 3], [10, 20, 30]]], dims=['lat_lon'])
    ...: node.eval(c)
Out[11]: 
<xarray.UnitsDataArray (lat_lon: 3)>
array([0., 1., 2.])
Coordinates:
  * lat_lon  (lat_lon) MultiIndex
  - lat      (lat_lon) float64 1.0 2.0 3.0
  - lon      (lat_lon) float64 10.0 20.0 30.0
Attributes:
    layer_style:  <podpac.core.style.Style object at 0x7fd7e5a83730>
    crs:          +proj=longlat +datum=WGS84 +no_defs +vunits=m
```
