### ISSUE TITLE
zarr is required to import podpac

### ISSUE THREAD

**Issue by jmilloy** [creare-com/podpac#288]
**Description**
The `Zarr` DataSource has a `group` trait that is an instance of `zarr.Group`, so the optional zarr library is actually required when importing podpac.core.data.types and, therefore, podpac. It should only raise the exception when the zarr datasource is used.

**Steps to Reproduce**

```
import podpac

node = podpac.data.Zarr('path/to/zarr')
```

**Expected Behavior**

 * The import should succeed.
 * Instantiating the Zarr node should raise a lazy_import ImportError.

**Observed Behavior**

 * The import raises the lazy_import ImportError:

    ```
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/jmilloy/Creare/Pipeline/podpac/podpac/__init__.py", line 36, in <module>
        from podpac.core.settings import settings
      File "/home/jmilloy/Creare/Pipeline/podpac/podpac/core/__init__.py", line 27, in <module>
        from .managers import aws_lambda 
      File "/home/jmilloy/Creare/Pipeline/podpac/podpac/core/managers/aws_lambda.py", line 15, in <module>
        from podpac.core.pipeline.output import FileOutput, Output
      File "/home/jmilloy/Creare/Pipeline/podpac/podpac/core/pipeline/__init__.py", line 2, in <module>
        from podpac.core.pipeline.pipeline import Pipeline, PipelineError
      File "/home/jmilloy/Creare/Pipeline/podpac/podpac/core/pipeline/pipeline.py", line 21, in <module>
        from podpac.core.data.types import ReprojectedSource, Array
      File "/home/jmilloy/Creare/Pipeline/podpac/podpac/core/data/types.py", line 701, in <module>
        class Zarr(DataSource):
      File "/home/jmilloy/Creare/Pipeline/podpac/podpac/core/data/types.py", line 703, in Zarr
        group = tl.ForwardDeclaredInstance(zarr.Group, allow_none=False)
      File "/home/jmilloy/Creare/Pipeline/_podpac_/lib/python3.6/site-packages/lazy_import/__init__.py", line 156, in __getattribute__
        _load_module(self)
      File "/home/jmilloy/Creare/Pipeline/_podpac_/lib/python3.6/site-packages/lazy_import    /__init__.py", line 537, in _load_module
        msg.format(**modclass._lazy_import_error_strings)), None)
      File "<string>", line 3, in raise_from
    ImportError: podpac.core.data.types attempted to use a functionality that requires module zarr, but it couldn't be loaded. Please install zarr and retry.
    ```

**Additional Notes**

A workaround would be to use `tl.Any()` for the `group` trait, and of course we could still validate the type manually using `@tl.validate`, but is there a better way?

For example, I tried to use `tl.ForwardDeclaredInstance("zarr.Group")` for the group trait, which allows `import podpac`, but does not successfully instantiate a Zarr node:

```
>>> import podpac
>>> podpac.data.Zarr
<class 'podpac.core.data.types.Zarr'>
>>> podpac.data.Zarr()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jmilloy/Creare/Pipeline/_podpac_/lib/python3.6/site-packages/traitlets/traitlets.py", line 958, in __new__
    inst.setup_instance(*args, **kwargs)
  File "/home/jmilloy/Creare/Pipeline/_podpac_/lib/python3.6/site-packages/traitlets/traitlets.py", line 986, in setup_instance
    super(HasTraits, self).setup_instance(*args, **kwargs)
  File "/home/jmilloy/Creare/Pipeline/_podpac_/lib/python3.6/site-packages/traitlets/traitlets.py", line 977, in setup_instance
    value.instance_init(self)
  File "/home/jmilloy/Creare/Pipeline/_podpac_/lib/python3.6/site-packages/traitlets/traitlets.py", line 1691, in instance_init
    self._resolve_classes()
  File "/home/jmilloy/Creare/Pipeline/_podpac_/lib/python3.6/site-packages/traitlets/traitlets.py", line 1696, in _resolve_classes
    self.klass = self._resolve_string(self.klass)
  File "/home/jmilloy/Creare/Pipeline/_podpac_/lib/python3.6/site-packages/traitlets/traitlets.py", line 1718, in _resolve_string
    return import_item('.'.join([modname, string]))
  File "/home/jmilloy/Creare/Pipeline/_podpac_/lib/python3.6/site-packages/traitlets/utils/importstring.py", line 34, in import_item
    module = __import__(package, fromlist=[obj])
ModuleNotFoundError: No module named 'podpac.core.data.types.zarr'; 'podpac.core.data.types' is not a package
```

**Comment by jmilloy** [comment]
@mpu-creare @mlshapiro Do either of you know a good way to solve this issue? I don't really know how to use `ForwardDeclaredInstance` -- maybe I am using it incorrectly or maybe it is incompatible with lazy_import? Or is the `tl.Any()` workaround the best way?

**Comment by mpu-creare** [comment]
You may have to:
```
zarrGroup = lazy_class('zarr.Group')
...
    group = tl.Instance('zarrGroup')
    # or without the quotes
```

or you can also try:

```
group = tl.Instance('zarr.Group')  # as a string
```

**Comment by jmilloy** [comment]
Thanks. I had to use lazy_class and a ForwardDeclaredInstance with quotes.

```
zarrGroup = lazy_class('zarr.Group')
...
    group = tl.ForwardDeclaredInstance('zarrGroup')
```
