### ISSUE TITLE
Exception requesting stacked coordinates from a DataSource with unstacked native coordinates

### ISSUE THREAD

**Issue by jmilloy** [creare-com/podpac#29]
**Steps to Reproduce**
```
class MyNode(NumpyArray):
    source = np.arange(10000.).reshape(100, 100)

    def get_native_coordinates(self):
        return Coordinate(lat=(-25, 25, 100), lon=(-25, 25, 100), order=['lat', 'lon'])

n = MyNode()
coords = Coordinate(lat_lon=[(-20, 20), (0, 5), 100])
out = n.execute(coords)
```

**Expected Behavior**
`out` should contain data interpolated from `MyNode.source`.

**Observed Behavior**

```
Traceback (most recent call last):
  File "jxm.py", line 29, in <module>
    a_out = n.execute(coords)
  File "/home/jmilloy/Pipeline/podpac/podpac/core/data/data.py", line 108, in execute
    self.interpolate_data(data_subset, coords_subset, coordinates)
  File "/home/jmilloy/Pipeline/podpac/podpac/core/data/data.py", line 292, in interpolate_data
    grid=False)
  File "/home/jmilloy/Pipeline/podpac/podpac/core/data/data.py", line 472, in interpolate_irregular_grid
    x, y = coords_i_dst['lon']
TypeError: list indices must be integers, not unicode
```

**Additional Notes**
See also #28

**Comment by jmilloy** [comment]
At least partially implemented in 805e735.
