### ISSUE TITLE
Rasterio exception using integer array as DataSource source 

### ISSUE THREAD

**Issue by jmilloy** [creare-com/podpac#30]
**Description**
Defining a DataSource node with a integer array as the source results in a rasterio exception when evaluating the node. The no-data value during interpolation using rasterio is `np.nan` which is invalid for integer inputs.

**Steps to Reproduce**
```
class A(NumpyArray):
    source = np.arange(10000).reshape(100, 100)

    def get_native_coordinates(self):
        return Coordinate(lat=(-25, 25, 100), lon=(-25, 25, 100), order=['lat', 'lon'])

a = A()
coords = Coordinate(lat=(0, 10, 80), lon=(0, 10, 80), order=['lat', 'lon'])
out = a.execute(coords)
```

**Observed Behavior**
```
Traceback (most recent call last):
  File "jxm.py", line 37, in <module>
    out = a.execute(coords)
  File "/home/jmilloy/Pipeline/podpac/podpac/core/data/data.py", line 108, in execute
    self.interpolate_data(data_subset, coords_subset, coordinates)
  File "/home/jmilloy/Pipeline/podpac/podpac/core/data/data.py", line 270, in interpolate_data
    return self.rasterio_interpolation(data_src, coords_src, data_dst, coords_dst)
  File "/home/jmilloy/Pipeline/podpac/podpac/core/data/data.py", line 393, in rasterio_interpolation
    resampling=getattr(Resampling, self.interpolation)
  File "/usr/local/lib/python2.7/dist-packages/rasterio-1.0a9-py2.7-linux-x86_64.egg/rasterio/env.py", line 275, in wrapper
    return f(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/rasterio-1.0a9-py2.7-linux-x86_64.egg/rasterio/warp.py", line 286, in reproject
    init_dest_nodata, **kwargs)
  File "rasterio/_warp.pyx", line 277, in rasterio._warp._reproject (rasterio/_warp.cpp:4742)
ValueError: src_nodata must be in valid range for source dtype
```

**Expected Behavior**
A `traitlets.TraitsError` or `ValueError` exception is raised during node initialization.

**Comment by jmilloy** [comment]
@mpu-creare Will you select one of the three proposed expected behaviors (or edit with a different one...) and then assign back to me or mls as appropriate?

**Comment by mpu-creare** [comment]
Supporting integer data is `nice-to-have` and an optimization at this stage. We can revisit in the future. 

Let's choose 2. `A traitlets.TraitsError or ValueError exception is raised during node initialization.` with a sane error telling users to convert the data to float. At least that way it's not silent. 

Ultimately we'd like to support option 3, since a lot of datasets use integers with a no-data integer value.

**Comment by mlshapiro** [comment]
this seems related to the data source handling - unless you get there first, I will try to handle

**Comment by mlshapiro** [comment]
This has been fixed in previous refactor:


```python
from podpac import Coordinates, clinspace
from podpac.data import Array
import numpy as np

class A(Array):
    source = np.arange(10000).reshape(100, 100)

    def get_native_coordinates(self):
        return Coordinates([clinspace(-25, 25, 100), clinspace(-25, 25, 100)], ['lat', 'lon'])

a = A()
coords = Coordinates([clinspace(0, 10, 80), clinspace(0, 10, 80)], ['lat', 'lon'])
out = a.eval(coords)
```
