### ISSUE TITLE
File cache can't deserialized cached DataArray with an empty time dimension

### ISSUE THREAD

**Issue by jmilloy** [creare-com/podpac#441]
**Description**

The file cache can serialize and put a DataArray with an empty time dimension, but it cannot deserialize it when getting the cached entry later.

**Steps to Reproduce**

I believe this is actually a bug in xarray:

```
import numpy as np
import xarray as xr

data = xr.DataArray(np.empty((1, 2)), dims=['a', 'b'], coords={'a': [np.datetime64('2021-01-01')], 'b':  [1, 2]})
selected = data[[]]
s = selected.to_netcdf()
x = xr.open_dataarray(s)
```

**Expected Behavior**

`selected` and and `x` should be the same.

**Observed Behavior**

```
>>> x = xr.open_dataarray(s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jmilloy/Creare/Pipeline/_podpac-38_/lib/python3.8/site-packages/xarray/backends/api.py", line 701, in open_dataarray
    dataset = open_dataset(
  File "/home/jmilloy/Creare/Pipeline/_podpac-38_/lib/python3.8/site-packages/xarray/backends/api.py", line 575, in open_dataset
    ds = maybe_decode_store(store, chunks)
  File "/home/jmilloy/Creare/Pipeline/_podpac-38_/lib/python3.8/site-packages/xarray/backends/api.py", line 471, in maybe_decode_store
    ds = conventions.decode_cf(
  File "/home/jmilloy/Creare/Pipeline/_podpac-38_/lib/python3.8/site-packages/xarray/conventions.py", line 600, in decode_cf
    ds = Dataset(vars, attrs=attrs)
  File "/home/jmilloy/Creare/Pipeline/_podpac-38_/lib/python3.8/site-packages/xarray/core/dataset.py", line 630, in __init__
    variables, coord_names, dims, indexes, _ = merge_data_and_coords(
  File "/home/jmilloy/Creare/Pipeline/_podpac-38_/lib/python3.8/site-packages/xarray/core/merge.py", line 467, in merge_data_and_coords
    return merge_core(
  File "/home/jmilloy/Creare/Pipeline/_podpac-38_/lib/python3.8/site-packages/xarray/core/merge.py", line 594, in merge_core
    collected = collect_variables_and_indexes(aligned)
  File "/home/jmilloy/Creare/Pipeline/_podpac-38_/lib/python3.8/site-packages/xarray/core/merge.py", line 278, in collect_variables_and_indexes
    variable = as_variable(variable, name=name)
  File "/home/jmilloy/Creare/Pipeline/_podpac-38_/lib/python3.8/site-packages/xarray/core/variable.py", line 160, in as_variable
    obj = obj.to_index_variable()
  File "/home/jmilloy/Creare/Pipeline/_podpac-38_/lib/python3.8/site-packages/xarray/core/variable.py", line 528, in to_index_variable
    return IndexVariable(
  File "/home/jmilloy/Creare/Pipeline/_podpac-38_/lib/python3.8/site-packages/xarray/core/variable.py", line 2412, in __init__
    self._data = PandasIndexAdapter(self._data)
  File "/home/jmilloy/Creare/Pipeline/_podpac-38_/lib/python3.8/site-packages/xarray/core/indexing.py", line 1397, in __init__
    self.array = utils.safe_cast_to_index(array)
  File "/home/jmilloy/Creare/Pipeline/_podpac-38_/lib/python3.8/site-packages/xarray/core/utils.py", line 104, in safe_cast_to_index
    index = pd.Index(np.asarray(array), **kwargs)
  File "/home/jmilloy/Creare/Pipeline/_podpac-38_/lib/python3.8/site-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/home/jmilloy/Creare/Pipeline/_podpac-38_/lib/python3.8/site-packages/xarray/core/indexing.py", line 568, in __array__
    return np.asarray(array[self.key], dtype=None)
  File "/home/jmilloy/Creare/Pipeline/_podpac-38_/lib/python3.8/site-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/home/jmilloy/Creare/Pipeline/_podpac-38_/lib/python3.8/site-packages/xarray/coding/variables.py", line 70, in __array__
    return self.func(self.array)
  File "/home/jmilloy/Creare/Pipeline/_podpac-38_/lib/python3.8/site-packages/xarray/coding/times.py", line 194, in decode_cf_datetime
    dates = _decode_datetime_with_pandas(flat_num_dates, units, calendar)
  File "/home/jmilloy/Creare/Pipeline/_podpac-38_/lib/python3.8/site-packages/xarray/coding/times.py", line 159, in _decode_datetime_with_pandas
    pd.to_timedelta(flat_num_dates.min(), delta) + ref_date
  File "/home/jmilloy/Creare/Pipeline/_podpac-38_/lib/python3.8/site-packages/numpy/core/_methods.py", line 43, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation minimum which has no identity
```

**Additional Notes**

There is no problem if the empty dimension is a float dimension. The problem is the `flat_num_dates.min()` in the xarray time handling.

**Comment by jmilloy** [comment]
@mpu-creare I'll file this with xarray, but I can work around with a bit of a hack by converting the empty dimension to float and leaving a custom note in the metadata before serialization, and then converting back and deleting the metadat note after deserialization. I run into this in one of my SMAP tests. Do you think I should do that, or just change the test so that there isn't an empty selection, and let podpac disk caching fail when this happens until it gets fixed upstream?

**Comment by jmilloy** [comment]
Okay a little more digging and this is fixed in xarray master, just not released to stable yet. I guess I'll leave it.

https://github.com/pydata/xarray/commit/ed255736664f8f0b4ea199c8f91bffaa89522d03#diff-e1c5f34f91e5b8a5242d9499ca9ff2765f3d5b7956c28196f80e4c399b29b1a6

**Comment by mpu-creare** [comment]
Thanks for digging Jeff!
